// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NextHorizon.Data;

#nullable disable

namespace NextHorizon.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260415075036_AddQaInlineCommentDrafts")]
    partial class AddQaInlineCommentDrafts
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("NextHorizon.Data.ConsumerRef", b =>
                {
                    b.Property<int>("ConsumerId")
                        .HasColumnType("int")
                        .HasColumnName("consumer_id");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("first_name");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("last_name");

                    b.Property<string>("MiddleName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("middle_name");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("username");

                    b.HasKey("ConsumerId");

                    b.ToTable("Consumers", "dbo", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("NextHorizon.Data.PlatformUser", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("is_active");

                    b.HasKey("UserId");

                    b.ToTable("Users", "dbo", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("NextHorizon.Data.SellerRef", b =>
                {
                    b.Property<int>("SellerId")
                        .HasColumnType("int")
                        .HasColumnName("seller_id");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("SellerId");

                    b.ToTable("Sellers", "dbo", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("NextHorizon.Data.SupportAgentRecord", b =>
                {
                    b.Property<int>("ChatId")
                        .HasColumnType("int")
                        .HasColumnName("ChatID");

                    b.Property<string>("AgentName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("AgentName");

                    b.Property<string>("AgentStatus")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("AgentStatus");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    b.HasKey("ChatId");

                    b.ToTable("Agents", "dbo", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("NextHorizon.Messaging.Models.ConversationMessage", b =>
                {
                    b.Property<long>("MessageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("MessageId"));

                    b.Property<string>("AttachmentUrl")
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int>("ConversationId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int>("SenderUserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("SentAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.HasKey("MessageId");

                    b.HasIndex("SenderUserId");

                    b.HasIndex("ConversationId", "SentAt")
                        .IsDescending(false, true);

                    b.ToTable("MessagingMessages", (string)null);
                });

            modelBuilder.Entity("NextHorizon.Messaging.Models.MessageConversation", b =>
                {
                    b.Property<int>("ConversationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ConversationId"));

                    b.Property<DateTime?>("BuyerLastReadAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("BuyerUserId")
                        .HasColumnType("int");

                    b.Property<byte>("ContextType")
                        .HasColumnType("tinyint");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<DateTime?>("LastMessageAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("OrderId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("SellerLastReadAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("SellerUserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.HasKey("ConversationId");

                    b.HasIndex("BuyerUserId");

                    b.HasIndex("LastMessageAt");

                    b.HasIndex("SellerUserId");

                    b.HasIndex("OrderId", "ContextType")
                        .IsUnique()
                        .HasFilter("[ContextType] = 2");

                    b.HasIndex("BuyerUserId", "SellerUserId", "ContextType")
                        .IsUnique()
                        .HasFilter("[ContextType] = 1");

                    b.ToTable("MessagingConversations", null, t =>
                        {
                            t.HasCheckConstraint("CK_MessagingConversations_ContextType", "[ContextType] IN (1, 2)");

                            t.HasCheckConstraint("CK_MessagingConversations_ContextType_Order", "([ContextType] = 1 AND [OrderId] IS NULL) OR ([ContextType] = 2 AND [OrderId] IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("NextHorizon.Models.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ConsumerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("ConsumerId")
                        .IsUnique()
                        .HasFilter("[ConsumerId] IS NOT NULL");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Customers", "dbo", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("NextHorizon.Models.HelpCenter.FaqRecord", b =>
                {
                    b.Property<int>("FaqId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("FaqID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FaqId"));

                    b.Property<string>("Answer")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)")
                        .HasColumnName("Answer");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)")
                        .HasColumnName("Category");

                    b.Property<DateTime>("DateAdded")
                        .HasColumnType("datetime2")
                        .HasColumnName("DateAdded");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("datetime2")
                        .HasColumnName("LastUpdated");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("Question");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)")
                        .HasColumnName("Status");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.Property<string>("UserType")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)")
                        .HasColumnName("UserType");

                    b.HasKey("FaqId");

                    b.ToTable("FAQs", "dbo", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("NextHorizon.Models.HelpCenter.LiveAgentSession", b =>
                {
                    b.Property<int>("LiveAgentSessionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LiveAgentSessionId"));

                    b.Property<string>("CategorySlug")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("CategoryTitle")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<int?>("ConsumerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<byte>("EndedReason")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasDefaultValue((byte)0);

                    b.Property<string>("FirstQuestion")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)")
                        .HasDefaultValue("");

                    b.Property<byte>("Status")
                        .HasColumnType("tinyint");

                    b.Property<int>("SupportFaqId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("LiveAgentSessionId");

                    b.HasIndex("ConsumerId");

                    b.HasIndex("SupportFaqId")
                        .IsUnique();

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasFilter("[Status] <> 3");

                    b.HasIndex("UserId", "Status", "CreatedAt")
                        .IsDescending(false, false, true);

                    b.ToTable("LiveAgentSessions", (string)null);
                });

            modelBuilder.Entity("NextHorizon.Models.HelpCenter.SupportContactChannel", b =>
                {
                    b.Property<int>("SupportContactChannelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SupportContactChannelId"));

                    b.Property<string>("ActionHref")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<string>("ChannelType")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("DisplayText")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)");

                    b.HasKey("SupportContactChannelId");

                    b.HasIndex("IsActive", "DisplayOrder");

                    b.ToTable("SupportContactChannels", (string)null);

                    b.HasData(
                        new
                        {
                            SupportContactChannelId = 1,
                            ActionHref = "mailto:support@nexthorizon.com",
                            ChannelType = "email",
                            DisplayOrder = 1,
                            DisplayText = "support@nexthorizon.com",
                            IsActive = true,
                            Label = "Email Support",
                            Value = "support@nexthorizon.com"
                        },
                        new
                        {
                            SupportContactChannelId = 2,
                            ActionHref = "tel:+18001234567",
                            ChannelType = "phone",
                            DisplayOrder = 2,
                            DisplayText = "+1 (800) 123-4567",
                            IsActive = true,
                            Label = "Phone Support",
                            Value = "+18001234567"
                        },
                        new
                        {
                            SupportContactChannelId = 3,
                            ActionHref = "/consumer/messenger/",
                            ChannelType = "chat",
                            DisplayOrder = 3,
                            DisplayText = "Open live support chat",
                            IsActive = true,
                            Label = "Live Chat",
                            Value = "/consumer/messenger/"
                        },
                        new
                        {
                            SupportContactChannelId = 4,
                            ActionHref = "",
                            ChannelType = "hours",
                            DisplayOrder = 4,
                            DisplayText = "Mon-Fri, 9AM-6PM (local time)",
                            IsActive = true,
                            Label = "Support Hours",
                            Value = "Mon-Fri, 9AM-6PM (local time)"
                        });
                });

            modelBuilder.Entity("NextHorizon.Models.HelpCenter.SupportFaqRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AgentId")
                        .HasColumnType("int")
                        .HasColumnName("AgentId");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Category");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatedAt");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("int")
                        .HasColumnName("DurationMinutes");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("EndTime");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Question");

                    b.Property<DateTime?>("StartTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("StartTime");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Status");

                    b.Property<string>("UserType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("UserType");

                    b.HasKey("Id");

                    b.ToTable("SupportFAQs", "dbo", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("NextHorizon.Models.HelpCenter.SupportMessage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ConversationId")
                        .HasColumnType("int")
                        .HasColumnName("ConversationId");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatedAt");

                    b.Property<string>("MessageText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("MessageText");

                    b.Property<int>("SenderId")
                        .HasColumnType("int")
                        .HasColumnName("SenderId");

                    b.Property<string>("SenderRole")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("SenderRole");

                    b.HasKey("Id");

                    b.ToTable("SupportMessages", "dbo", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("NextHorizon.Models.HelpCenter.SupportTicket", b =>
                {
                    b.Property<int>("SupportTicketId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SupportTicketId"));

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<int?>("ConsumerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("FaqCategory")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("ReferenceCode")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<byte>("Status")
                        .HasColumnType("tinyint");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("SupportTicketId");

                    b.HasIndex("ConsumerId");

                    b.HasIndex("ReferenceCode")
                        .IsUnique();

                    b.HasIndex("Status", "CreatedAt")
                        .IsDescending(false, true);

                    b.HasIndex("UserId", "CreatedAt")
                        .IsDescending(false, true);

                    b.ToTable("SupportTickets", (string)null);
                });

            modelBuilder.Entity("NextHorizon.Models.QA.QaReview", b =>
                {
                    b.Property<int>("QaReviewId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("QaReviewId"));

                    b.Property<decimal>("AccuracyAverage")
                        .HasColumnType("decimal(5,2)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("InlineCommentsJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("{}");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<decimal>("OverallPercent")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("ResolutionAverage")
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("ReviewerName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("ReviewerStaffId")
                        .HasColumnType("int");

                    b.Property<bool>("SubmittedToAgent")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("SubmittedToAgentAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("SupportFaqId")
                        .HasColumnType("int");

                    b.Property<decimal>("ToneAverage")
                        .HasColumnType("decimal(5,2)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("QaReviewId");

                    b.HasIndex("SupportFaqId")
                        .IsUnique();

                    b.ToTable("QaReviews", (string)null);
                });

            modelBuilder.Entity("NextHorizon.Models.QA.QaReviewInlineCommentDraft", b =>
                {
                    b.Property<int>("QaReviewInlineCommentDraftId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("QaReviewInlineCommentDraftId"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("InlineCommentsJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("{}");

                    b.Property<int>("SupportFaqId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedByName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("UpdatedByStaffId")
                        .HasColumnType("int");

                    b.HasKey("QaReviewInlineCommentDraftId");

                    b.HasIndex("SupportFaqId")
                        .IsUnique();

                    b.ToTable("QaReviewInlineCommentDrafts", (string)null);
                });

            modelBuilder.Entity("NextHorizon.Models.QA.QaReviewQuestionScore", b =>
                {
                    b.Property<int>("QaReviewQuestionScoreId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("QaReviewQuestionScoreId"));

                    b.Property<int>("QaReviewId")
                        .HasColumnType("int");

                    b.Property<string>("QuestionKey")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<int>("Score")
                        .HasColumnType("int");

                    b.HasKey("QaReviewQuestionScoreId");

                    b.HasIndex("QaReviewId", "QuestionKey")
                        .IsUnique();

                    b.ToTable("QaReviewQuestionScores", (string)null);
                });

            modelBuilder.Entity("NextHorizon.Modules.MemberTracker.Models.MemberUpload", b =>
                {
                    b.Property<int>("UploadId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UploadId"));

                    b.Property<DateTime>("ActivityDate")
                        .HasColumnType("date");

                    b.Property<string>("ActivityName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<int?>("AvgPaceSecPerKm")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<decimal>("DistanceKm")
                        .HasPrecision(6, 2)
                        .HasColumnType("decimal(6,2)");

                    b.Property<int>("MovingTimeSec")
                        .HasColumnType("int");

                    b.Property<string>("ProofUrl")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<int?>("Steps")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("UploadId");

                    b.HasIndex("ActivityDate")
                        .IsDescending();

                    b.HasIndex("UserId", "CreatedAt")
                        .IsDescending(false, true);

                    b.ToTable("MemberUploads", (string)null);
                });

            modelBuilder.Entity("NextHorizon.Messaging.Models.ConversationMessage", b =>
                {
                    b.HasOne("NextHorizon.Messaging.Models.MessageConversation", "Conversation")
                        .WithMany("Messages")
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NextHorizon.Data.PlatformUser", null)
                        .WithMany()
                        .HasForeignKey("SenderUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Conversation");
                });

            modelBuilder.Entity("NextHorizon.Messaging.Models.MessageConversation", b =>
                {
                    b.HasOne("NextHorizon.Data.ConsumerRef", null)
                        .WithMany()
                        .HasForeignKey("BuyerUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NextHorizon.Data.SellerRef", null)
                        .WithMany()
                        .HasForeignKey("SellerUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("NextHorizon.Models.Customer", b =>
                {
                    b.HasOne("NextHorizon.Data.ConsumerRef", null)
                        .WithMany()
                        .HasForeignKey("ConsumerId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("NextHorizon.Models.HelpCenter.LiveAgentSession", b =>
                {
                    b.HasOne("NextHorizon.Data.ConsumerRef", null)
                        .WithMany()
                        .HasForeignKey("ConsumerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("NextHorizon.Data.PlatformUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("NextHorizon.Models.HelpCenter.SupportTicket", b =>
                {
                    b.HasOne("NextHorizon.Data.ConsumerRef", null)
                        .WithMany()
                        .HasForeignKey("ConsumerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("NextHorizon.Data.PlatformUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("NextHorizon.Models.QA.QaReviewQuestionScore", b =>
                {
                    b.HasOne("NextHorizon.Models.QA.QaReview", "Review")
                        .WithMany("QuestionScores")
                        .HasForeignKey("QaReviewId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Review");
                });

            modelBuilder.Entity("NextHorizon.Modules.MemberTracker.Models.MemberUpload", b =>
                {
                    b.HasOne("NextHorizon.Data.ConsumerRef", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("NextHorizon.Messaging.Models.MessageConversation", b =>
                {
                    b.Navigation("Messages");
                });

            modelBuilder.Entity("NextHorizon.Models.QA.QaReview", b =>
                {
                    b.Navigation("QuestionScores");
                });
#pragma warning restore 612, 618
        }
    }
}
